project_id = "rclpyipeytqbamiwcuih"

[functions.paypal-management]
verify_jwt = true

[functions.chat-management]
verify_jwt = true

[functions.extract-addon-context]
verify_jwt = true

[functions.admin-utilities]
verify_jwt = false